title: BeLeap Blog
email: beleap@beleap.dev
description: >-
  Creating something unnecessary
baseurl: ""
url: "https://beleap.dev"
twitter_username: beleap_
github_username:  BeLeap

# So Simple Configurations
read_time: true
words_per_minute: 200
mathjax:
  enable: true
search_full_content: true
google_fonts:
  - name: "IBM Plex Sans KR"
    weights: "400,400i,700,700i"

remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
