title: BeLeap Blog
email: beleap@beleap.dev
description: >-
  Creating something unnecessary
baseurl: ""
url: "https://beleap.dev"
twitter_username: beleap_
github_username:  BeLeap

markdown: kramdown
mathjax:
  enable: true
search_full_content: true
google_fonts:
  - name: "IBM Plex Sans KR"
    weights: "400,400i,700,700i"
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

feed:
  path: atom.xml

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache


author:
  name: "BeLeap"
  avatar: "https://avatars.githubusercontent.com/u/46488521?v=4"
  bio: Creating something unnecessary
  links:
    - label: Twitter
      url: https://twitter.com/beleap_
      icon: fab fa-twitter-square
    - label: GitHub
      url: https://github.com/BeLeap
      icon: fab fa-github-square

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      author_profile: true
      share: true
      related: true
