title: BeLeap Blog
email: beleap@beleap.dev
description: >-
  Creating something unnecessary
baseurl: ""
url: "https://beleap.dev"
twitter_username: beleap_
github_username:  BeLeap

# So Simple Configurations
read_time: true
words_per_minute: 200
markdown: kramdown
mathjax:
  enable: true
search_full_content: true
google_fonts:
  - name: "IBM Plex Sans KR"
    weights: "400,400i,700,700i"
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

feed:
  path: atom.xml

remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

footer_links:
  - title: Twitter
    url: https://twitter.com/beleap_
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/BeLeap
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
