baseURL = 'https://beleap.dev/'
languageCode = 'en-us'
title = 'BeLeap Blog'
theme = 'archie'

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Creating something unnecessary"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/BeLeap"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/beleap_/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
