baseURL = 'https://beleap.dev/'
languageCode = 'en-us'
title = 'BeLeap Blog'
theme = 'archie'

[params]
	mode="auto"
	useCDN=false
	subtitle = "Creating something unnecessary"
	mathjax = true
	katex = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/BeLeap"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/beleap_/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
