import Header from '@/components/Header'
import './globals.css'
import styles from './layout.module.css'

export const metadata = {
  title: 'BeLeap Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <Header />
        {children}
      </body>
    </html>
  )
}
